database_details:
  host: localhost
  port: 3306
  database: aircraft_db

data_extraction_details:
  raw_data_dir : data
  
  train_data_path : train_FD001.txt
  test_data_path : test_FD001.txt
  test_target_path : RUL_FD001.txt

  extracted_data_dir : data_extraction
  
  extracted_train_data_path : train_data.csv
  extracted_test_data_path : test_data.csv
  extracted_test_target_path : test_data_target.csv

  feature_columns : ['engine_id','cycle','op_set_1','op_set_2','op_set_3','sensor_1','sensor_2','sensor_3','sensor_4','sensor_5','sensor_6','sensor_7','sensor_8','sensor_9','sensor_10','sensor_11','sensor_12','sensor_13','sensor_14','sensor_15','sensor_16','sensor_17','sensor_18','sensor_19','sensor_20','sensor_21']
  target_column : ['RUL']