TRAIN_FEATURES = """
CREATE TABLE IF NOT EXISTS train_features (

engine_id INT NOT NULL,
cycle INT NOT NULL,
sensor_2_norm FLOAT,
sensor_3_norm FLOAT,
sensor_4_norm FLOAT,
sensor_7_norm FLOAT,
sensor_8_norm FLOAT,
sensor_9_norm FLOAT,
sensor_11_norm FLOAT,
sensor_12_norm FLOAT,
sensor_13_norm FLOAT,
sensor_14_norm FLOAT,
sensor_15_norm FLOAT,
sensor_17_norm FLOAT,
sensor_20_norm FLOAT,
sensor_21_norm FLOAT,
cycle_count INT,
cycle_count_norm FLOAT,
sensor_2_std_15 FLOAT,
sensor_3_std_15 FLOAT,
sensor_4_std_15 FLOAT,
sensor_7_std_15 FLOAT,
sensor_8_std_15 FLOAT,
sensor_9_std_15 FLOAT,
sensor_11_std_15 FLOAT,
sensor_12_std_15 FLOAT,
sensor_13_std_15 FLOAT,
sensor_14_std_15 FLOAT,
sensor_15_std_15 FLOAT,
sensor_17_std_15 FLOAT,
sensor_20_std_15 FLOAT,
sensor_21_std_15 FLOAT,
sensor_2_delta3 FLOAT,
sensor_3_delta3 FLOAT,
sensor_4_delta3 FLOAT,
sensor_7_delta3 FLOAT,
sensor_8_delta3 FLOAT,
sensor_9_delta3 FLOAT,
sensor_11_delta3 FLOAT,
sensor_12_delta3 FLOAT,
sensor_13_delta3 FLOAT,
sensor_14_delta3 FLOAT,
sensor_15_delta3 FLOAT,
sensor_17_delta3 FLOAT,
sensor_20_delta3 FLOAT,
sensor_21_delta3 FLOAT,
sensor_2_slope20 FLOAT,
sensor_3_slope20 FLOAT,
sensor_4_slope20 FLOAT,
sensor_7_slope20 FLOAT,
sensor_8_slope20 FLOAT,
sensor_9_slope20 FLOAT,
sensor_11_slope20 FLOAT,
sensor_12_slope20 FLOAT,
sensor_13_slope20 FLOAT,
sensor_14_slope20 FLOAT,
sensor_15_slope20 FLOAT,
sensor_17_slope20 FLOAT,
sensor_20_slope20 FLOAT,
sensor_21_slope20 FLOAT,
health_index FLOAT,
sensor_2_absdev FLOAT,
sensor_3_absdev FLOAT,
sensor_4_absdev FLOAT,
sensor_7_absdev FLOAT,
sensor_8_absdev FLOAT,
sensor_9_absdev FLOAT,
sensor_11_absdev FLOAT,
sensor_12_absdev FLOAT,
sensor_13_absdev FLOAT,
sensor_14_absdev FLOAT,
sensor_15_absdev FLOAT,
sensor_17_absdev FLOAT,
sensor_20_absdev FLOAT,
sensor_21_absdev FLOAT,
RUL_capped FLOAT,
RUL_scaled FLOAT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (engine_id, cycle)
);
"""

TEST_FEATURES = """
CREATE TABLE IF NOT EXISTS test_features (
engine_id INT NOT NULL,
cycle INT NOT NULL,
sensor_2_norm FLOAT,
sensor_3_norm FLOAT,
sensor_4_norm FLOAT,
sensor_7_norm FLOAT,
sensor_8_norm FLOAT,
sensor_9_norm FLOAT,
sensor_11_norm FLOAT,
sensor_12_norm FLOAT,
sensor_13_norm FLOAT,
sensor_14_norm FLOAT,
sensor_15_norm FLOAT,
sensor_17_norm FLOAT,
sensor_20_norm FLOAT,
sensor_21_norm FLOAT,
cycle_count INT,
cycle_count_norm FLOAT,
sensor_2_std_15 FLOAT,
sensor_3_std_15 FLOAT,
sensor_4_std_15 FLOAT,
sensor_7_std_15 FLOAT,
sensor_8_std_15 FLOAT,
sensor_9_std_15 FLOAT,
sensor_11_std_15 FLOAT,
sensor_12_std_15 FLOAT,
sensor_13_std_15 FLOAT,
sensor_14_std_15 FLOAT,
sensor_15_std_15 FLOAT,
sensor_17_std_15 FLOAT,
sensor_20_std_15 FLOAT,
sensor_21_std_15 FLOAT,
sensor_2_delta3 FLOAT,
sensor_3_delta3 FLOAT,
sensor_4_delta3 FLOAT,
sensor_7_delta3 FLOAT,
sensor_8_delta3 FLOAT,
sensor_9_delta3 FLOAT,
sensor_11_delta3 FLOAT,
sensor_12_delta3 FLOAT,
sensor_13_delta3 FLOAT,
sensor_14_delta3 FLOAT,
sensor_15_delta3 FLOAT,
sensor_17_delta3 FLOAT,
sensor_20_delta3 FLOAT,
sensor_21_delta3 FLOAT,
sensor_2_slope20 FLOAT,
sensor_3_slope20 FLOAT,
sensor_4_slope20 FLOAT,
sensor_7_slope20 FLOAT,
sensor_8_slope20 FLOAT,
sensor_9_slope20 FLOAT,
sensor_11_slope20 FLOAT,
sensor_12_slope20 FLOAT,
sensor_13_slope20 FLOAT,
sensor_14_slope20 FLOAT,
sensor_15_slope20 FLOAT,
sensor_17_slope20 FLOAT,
sensor_20_slope20 FLOAT,
sensor_21_slope20 FLOAT,
health_index FLOAT,
sensor_2_absdev FLOAT,
sensor_3_absdev FLOAT,
sensor_4_absdev FLOAT,
sensor_7_absdev FLOAT,
sensor_8_absdev FLOAT,
sensor_9_absdev FLOAT,
sensor_11_absdev FLOAT,
sensor_12_absdev FLOAT,
sensor_13_absdev FLOAT,
sensor_14_absdev FLOAT,
sensor_15_absdev FLOAT,
sensor_17_absdev FLOAT,
sensor_20_absdev FLOAT,
sensor_21_absdev FLOAT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (engine_id, cycle)
);
"""

TEST_TARGETS = """
CREATE TABLE IF NOT EXISTS test_targets (
engine_id INT NOT NULL,
RUL INT,
RUL_capped FLOAT,
RUL_scaled FLOAT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (engine_id)
);
"""